# Generated by Django 6.0.4 on 2026-04-29 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=200)),
                ('congregation', models.CharField(max_length=200)),
                ('plate_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('is_checked_out', models.BooleanField(default=False)),
                ('tally', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.tally')),
            ],
        ),
    ]
