# Generated by Django 6.0.4 on 2026-04-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='banner_bg_color',
            field=models.CharField(default='#1e293b', help_text='HEX code for banner background', max_length=7),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='banner_text_color',
            field=models.CharField(default='#ffffff', help_text='HEX code for banner text', max_length=7),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='tally_active_color',
            field=models.CharField(default='#3b82f6', help_text='Background color when a tally is selected', max_length=7),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='tally_bg_color',
            field=models.CharField(default='#ffffff', help_text='Default background for tally buttons', max_length=7),
        ),
    ]
